### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by ib00** [rkaehn/cr_task.h#4]
There seem to be a couple of memory leaks. Memory is allocated in _cr_pool_pop() and cr_executor_create() 
that is never freed.

**Comment by rkaehn** [comment]
The current version of the library had the main design goal of being as simple as possible. As part of that, I made the decision to delegate the responsibility of freeing resources to the operating system on process exit. Apart from calling free() on memory allocated with malloc(), this would otherwise involve waiting for running tasks, communicating with the worker threads for them to exit, setting up callbacks to inform the library user of progress or blocking, amongst others. However, I have taken notice of the feedback and might address it in future versions.
